### ISSUE TITLE
QEMU: Image format not specified

### ISSUE THREAD

**Issue by johnandersen777** [tpm2-software/tpm2-tcti-uefi#20]
```
WARNING: Image format was not specified for 'json:{"fat-type": 0, "dir": "./example", "driver": "vvfat", "floppy": false, "rw": true}' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
```

**Comment by flihp** [comment]
If you put this warning into your favorite search engine there are lots of hits. Spent a minute searching here and everything I'm finding says that this warning is harmless (unless of course QEMU fails after). You haven't provided any data other than the warning text but based on #21 it looks like your QEMU is booting OVMF. Lots of guessing going on here but you haven't provided much context so I'll guess again that this isn't really a problem. If you disagree please reopen with data.

**Comment by johnandersen777** [comment]
For reference: https://bugs.launchpad.net/qemu/+bug/1474263
